name: PullRequest Validation
# This workflow is triggered on changes to pull request.
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make lint
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v1
        with:
          name: dialect-chrome-extension
          path: dialect-chrome-extension.zip